lesson_4/example_app/config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/all_users', to: 'users#index'
end

lesson_4/example_app/app/models/user.rb
class User < ApplicationRecord
end

lesson_4/example_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    User.create(user_params)

    redirect_to users_path
  end

  def edit
  end

  def update
    @user.update(user_params)

    redirect_to @user
  end

  def destroy
    @user.destroy

    redirect_to users_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :age)
  end
end

lesson_4/example_app/app/helpers/users_helper.rb
module UsersHelper
end

lesson_4/example_app/app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :age %>
  <%= f.submit %>
<% end %>

lesson_4/example_app/app/views/users/index.erb
<h1>Index</h1>

<% @users.each do |user| %>
  <p>
    <span>
      <%= user.name%>
    </span>

    <%= link_to ' Show', user %>
    <%= link_to ' Edit', edit_user_url(user) %>
    <%= link_to ' Destroy', user, method: :delete %>
  </p>
<% end %>

lesson_4/example_app/app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :age %>
  <%= f.submit %> 
<% end %>

lesson_4/example_app/app/views/users/show.erb
<h1>Show</h1>
<h3><%= @user.name %></h3>

<%= link_to 'All users', all_users_path %>